### ISSUE TITLE
Support for hexadecimal ids

### ISSUE THREAD

**Issue by DellanX** [mdegat01/addon-amr2mqtt#108]
**Is your feature request related to a problem? Please describe.**
My meter has an 'A' in its ID, but the schema only supports decimal characters.

**Describe the solution you'd like**
The configuration to support hexadecimal id's. 

**Describe alternatives you've considered**
None, gated

**Additional context**
On both my bill, and the meter itself, I have an ID 11A7xxxx (omiting last four digits).

**Comment by DellanX** [comment]
Still an issue

**Comment by DellanX** [comment]
Issue still exists

**Comment by DellanX** [comment]
Still an issue

**Comment by DellanX** [comment]
Still an issue

**Comment by DellanX** [comment]
Still an issue

**Comment by DellanX** [comment]
Still an issue

**Comment by maxinux** [comment]
What do you see if you run with meters set to [] or running rtlamr outside of HA?

**Comment by DellanX** [comment]
It'll be a bit, getting married and don't have this all setup anymore
