### ISSUE TITLE
r900 Isn't Working

### ISSUE THREAD

**Issue by indigest** [mdegat01/addon-amr2mqtt#60]
I am using this addon with a Nooelec NESDR Mini on an RPI4B and I'm trying to pull data simultaneously from 4 sources:

1. Electric meter (SCM)
2. Gas meter (SCM+)
3. Water meter (r900)
4. Irrigation water meter (r900)

The electric and gas meters are working well but I am not able to get either of the r900 water meters working. I monitored the MQTT traffic and I'm not seeing any updates for the water meters.

The amr2mqtt logfile reports that it is listening to r900 and it does not have any of those ll+ messages that are indicative of a processing speed issue.

I tried the same dongle on my PC using rtl_tcp and rtlamr and I see the r900 messages show up.

Please let me know if you have any ideas.

amr2mqtt log:
```
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001
Using device 0: Generic RTL2832U OEM
Detached kernel driver
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Tuned to 100000000 Hz.
[13:47:17] INFO: Log level set to INFO
[13:47:17] INFO: Waiting for rtl_tcp...
Allocating 15 zero-copy buffers
[13:47:17] INFO: Handing over control to AMR2MQTT...
Signal caught, exiting!
Signal caught, exiting!
INFO:root:Starting rtlamr
INFO:root:Connecting to MQTT broker at core-mosquitto:1883
Allocating 15 zero-copy buffers
13:47:18.998596 decode.go:45: CenterFreq: 912600155
13:47:18.999194 decode.go:46: SampleRate: 2359296
13:47:18.999237 decode.go:47: DataRate: 32768
13:47:18.999265 decode.go:48: ChipLength: 72
13:47:18.999291 decode.go:49: PreambleSymbols: 32
13:47:18.999316 decode.go:50: PreambleLength: 4608
13:47:18.999341 decode.go:51: PacketSymbols: 128
13:47:18.999366 decode.go:52: PacketLength: 18432
13:47:18.999403 decode.go:59: Protocols: r900,scm,scm+
13:47:18.999432 decode.go:60: Preambles: 00000000000000001110010101100100,111110010101001100000,0001011010100011
13:47:18.999460 main.go:111: GainCount: 29
```

PC log (ID changed):
```
13:45:28.830497 decode.go:45: CenterFreq: 912380000
13:45:28.831142 decode.go:46: SampleRate: 2359296
13:45:28.831142 decode.go:47: DataRate: 32768
13:45:28.831142 decode.go:48: ChipLength: 72
13:45:28.831142 decode.go:49: PreambleSymbols: 32
13:45:28.831683 decode.go:50: PreambleLength: 4608
13:45:28.831683 decode.go:51: PacketSymbols: 128
13:45:28.831683 decode.go:52: PacketLength: 18432
13:45:28.831683 decode.go:59: Protocols: scm,scm+,r900
13:45:28.831683 decode.go:60: Preambles: 111110010101001100000,0001011010100011,00000000000000001110010101100100
13:45:28.831683 main.go:124: GainCount: 29
{Time:2022-04-10T13:45:38.141 R900:{ID:1234567890 Unkn1:0xA3 NoUse:36 BackFlow:0 Consumption:  114880 Unkn3:0x00 Leak: 0 LeakNow:0}}
```

Meter config (ID changed):
```
  - id: 12345674890
    protocol: r900
    name: Irrigation Water Meter
    type: water
    multiplier: 0.01
    unit_of_measurement: ft³
    precision: 2
```

**Comment by indigest** [comment]
I was able to resolve this locally. The problem is that my r900 messages are showing up with 8 fields, but the amr2mqtt.py is looking for messages with 9 fields.

With this change, I am able to receive from all 4 of my meters simultaneously.

```
            # R900 results have 8 fields
            elif fields_count == 8:
                msg_type = "r900"
                meter_id = str(amr_message[ID_FIELD])
                adjust_reading(
                    reading_time=amr_time,
                    meter_id=meter_id,
                    reading=amr_message,
                    consumption_field=CONSUMPTION_FIELD,
                )
```

**Comment by mdegat01** [comment]
Huh. I'm not sure how I screwed that up, it's clearly 9 [here](https://github.com/bemasher/rtlamr/wiki/Protocol#r900-consumption-message). Although I'll be honest, I don't have any r900 meters. I had my thing antenna search around to see if I could pick one up nearby to use for testing but wasn't able to find one. I'll get that fixed up though, sorry about that.

**Comment by mdegat01** [comment]
Wait, now I'm confused. That's not what the code of this addon says. I don't really know where that came from but here is what this addon says for R900 in the current stable version (v1.02):
https://github.com/mdegat01/addon-amr2mqtt/blob/05d79bc82a0b9612a0ad536a4b13655b30dbccc5/amr2mqtt/rootfs/amr2mqtt/amr2mqtt.py#L406-L415

Where did you get that? Are you using a fork or something?

**Comment by mdegat01** [comment]
Oh wait, I feel silly. You're saying they have 8, duh 🤦 

That's very strange since it doesn't match the rtlamr doc. Since I can't really do any testing or confirming of r900 meters myself maybe I'll just make it 8 or 9 fields. No other type of messages have that length so it doesn't create a conflict either way.

**Comment by indigest** [comment]
Thank you for fixing this! I'm currently using a locally modified copy but I'll switch back to this version upon the next release.

**Comment by indigest** [comment]
Thanks for the [v2.0.0](https://github.com/mdegat01/addon-amr2mqtt/releases/tag/v2.0.0) release. It looks good and I can see the r900 messages come in with MQTT Explorer.
