### ISSUE TITLE
Setting Center Frequency

### ISSUE THREAD

**Issue by gdam12886** [mdegat01/addon-amr2mqtt#69]
The meter that I am attempting to capture uses 917.58Mhz. I am able to use rtlamr on my PC set to that frequency and I pick up a number of meters. The addon uses 912.38Mhz as the center frequency and is not picking up any meters.

Can an option be added to the addon configuration to set the center frequency?

**Comment by mdegat01** [comment]
Sure seems reasonable. Is that what the value of this option looks like? A float basically? The doc just says this:
```
-centerfreq=0: center frequency to receive on
```
Want to properly validate the option so need to know if its used like this:
```
-centerfreq=912.38
```
or like this:
```
-centerfreq=912.38Mhz
```

**Comment by randysaz928** [comment]
I believe it is looking for float + M like:
912.380M or 915M
I believe rtlamr pretty much does nothing with it and just passes it to rtl_tcp.
