### ISSUE TITLE
After HAOS 8.5 / Home Assistant Core 2022.8.7 update Addon fails

### ISSUE THREAD

**Issue by bstempien** [mdegat01/addon-amr2mqtt#75]
**Describe the bug**
After the update to HAOS 8.5 / HA Core 2022.8.7 on my generic_x86 based HAOS setup this addon stopped working. 

The log file is filled with the same error:
17:43:49.026662 main.go:145: Error reading samples:  EOF
17:43:49.026677 main.go:145: Error reading samples:  EOF

**To Reproduce**

1. Start Addon after above updates.

I have also uninstalled and reinstalled the Addon, and then completely restarting the host. Neither action helped the situation. 

**Expected behavior**
Addon should feed MQTT messages to HA as before

**Logs**

```
After getting into debug mode so that I could see the logs from docker just as the Add-on starts, I get:

[17:46:41] INFO: Starting rtl_tcp daemon...
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001
Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Tuned to 100000000 Hz.
[17:46:43] INFO: Log level set to INFO
[17:46:43] INFO: Waiting for rtl_tcp...
Allocating 15 zero-copy buffers
[17:46:43] INFO: Handing over control to AMR2MQTT...
INFO:root:Starting rtlamr
INFO:root:Connecting to MQTT broker at core-mosquitto:1883
Signal caught, exiting!
Signal caught, exiting!
Allocating 15 zero-copy buffers
17:46:48.403071 decode.go:45: CenterFreq: 912380000
17:46:48.403450 decode.go:46: SampleRate: 2359296
17:46:48.403468 decode.go:47: DataRate: 32768
17:46:48.403481 decode.go:48: ChipLength: 72
17:46:48.403495 decode.go:49: PreambleSymbols: 32
17:46:48.403509 decode.go:50: PreambleLength: 4608
17:46:48.403524 decode.go:51: PacketSymbols: 116
17:46:48.403540 decode.go:52: PacketLength: 16704
17:46:48.403562 decode.go:59: Protocols: r900
17:46:48.403577 decode.go:60: Preambles: 00000000000000001110010101100100
17:46:48.403664 main.go:111: GainCount: 29
Signal caught, exiting!
Signal caught, exiting!
17:46:53.712976 main.go:145: Error reading samples:  read tcp 127.0.0.1:60772->127.0.0.1:1234: read: connection reset by peer

Then it just continuously dumps the above message after that. 
```

**Environment (please complete the following information):**

- Add-on version: 2.0
- Supervisor version: 2022.08.3
- Operating system: Home Assistant OS 8.5

**Additional context**
I can get into the docker image using the debug part of HAOS. While I know my way around Linux, docker is new to me. I am willing to gather whatever info is needed.

**Comment by mdegat01** [comment]
Hm strange. Do you have any other addons running trying to use the same USB device by any chance?

**Comment by bstempien** [comment]
I had nothing else using the radio stick. I have since moved the stick to a
Raspberry Pi and removed the Addon.
