### ISSUE TITLE
add sensors for other meter fields

### ISSUE THREAD

**Issue by craftyguy** [mdegat01/addon-amr2mqtt#79]
rtlamr reports several useful fields for the r900, like "leakNow" when there's an active leak detected by a water meter. having this be something like a binary sensor would be really useful because then I could make a HA alert trigger on it, for example.

I'm not sure if other meters / protocols have similarly useful fields besides the consumption value, but it might be useful to also report those too as new sensors?

**Comment by craftyguy** [comment]
bad auto-close bot, bad! (obviously this is still relevant since it's an unfulfilled request...)

**Comment by band8266** [comment]
It looks like those sensors do get exposed to home assistant, but they are disabled by default.   Go into the devices and Leak and Leak Now are under diagnostic section as disabled.  Just enabled them from there.

**Comment by craftyguy** [comment]
@band8266 hey thanks for the pointer! I went to Settings->Devices & Services->Devices (tab), and clicked on AMR2MQTT. I don't see any "diagnostic" section or anything that lists these missing sensors... am I looking in the wrong place?

**Comment by band8266** [comment]
It should be an MQTT device.   Settings > Devices & Services > Devices (tab) > ( Water Meter )
![Screen Shot 2022-11-08 at 3 56 47 PM](https://user-images.githubusercontent.com/23263863/200694177-5164b2de-9d74-4614-ac4e-24f3eb779bf2.png)

**Comment by craftyguy** [comment]
ah, found it, thanks a lot!
