### ISSUE TITLE
Water meter not populating MQTT auto-discovery fields correctly

### ISSUE THREAD

**Issue by jlboygenius** [mdegat01/addon-amr2mqtt#86]
**Describe the bug**
I've setup my meter configuration for my water meter. The fields are auto-populated into the MQTT auto-discovery topic incorrectly, which causes HA to not identify the sensor correctly and therefore can't be used in the as an Energy Dashboard water meter consumption sensor.

**To Reproduce**
Meter configuration:
- id: ******
  protocol: r900
  name: Watermeter
  type: water
  state_class: total_increasing
  device_class: water
  unit_of_measurement: gal

This is populated into the MQTT auto-discovery consumption config, but it is missing the flag for "device_class". It is also tagged as state_class: "total" instead of "total_increasing"

**Expected behavior**
Should populate as 
state_class: total_increasing
device_class: water

**Logs**

```
Include any relevant logs
```

**Environment (please complete the following information):**

- Add-on version: AMR2MQTT Current version: 2.1.2
- Supervisor version: [e.g.supervisor-2021.03.6]
- Operating system HA 2022.11.4

**Additional context**
If i go into MQTT-Explorer and re-publish 
Homeassistant\sensor\******(myid)\consumption\config and add in the device_class and update the state_class, I am able to find the sensor in the Energy Dashboard Config and select the sensor for water consumption.

Changing anything in the AMR2MQTT config and restarting will cause the MQTT settings to be over-written. I then have to go back in and re-add device_class: water and state_class: total_increasing to get things working again.

**Comment by jlboygenius** [comment]
I took a look at the code and it seemed like a fairly simple fix.

Please review pull request #87

**Comment by twojciac** [comment]
I'm seeing the same exact issue.  Can the maintainer review the pull request and merge if it looks okay?

**Comment by fabianluque** [comment]
Same here, just got water meter replaced (with a supported one), configured and I'm not able to add to energy dashboard as described above. Is there anything we can do to help merge and release this? Thanks!

**Comment by JohnnyPicnic** [comment]
Plus one for this. I'm not able to add my water meter or gas meter to the energy dashboard.

**Comment by jhstroebel** [comment]
Same... got around this by manually configuring by MQTT entities, but its a pain

**Comment by jlboygenius** [comment]
Sent @mdegat01 a message on Discord. maybe he gets them there? Hopefully has some time to review? Amr2mqtt is great and easy to setup. HA supports water usage tracking. This one little tweak makes it all work together easily.

**Comment by jlboygenius** [comment]
This is still an open issue. Not sure how to grab @mdegat01's attention to accept the pull request though.

**Comment by JohnnyPicnic** [comment]
I ended up switching to this one
https://github.com/cpyarger/Home-Assistant-Addons/tree/main/SDRMR
