### ISSUE TITLE
MQTT server is not reachable

### ISSUE THREAD

**Issue by reypm** [mdegat01/addon-amr2mqtt#96]
**Describe the bug**
AMR2MQTT add-on refuses to connect to the Mosquitto MQTT server.

**To Reproduce**

> For this to be reproducible you will need to be on the latest version of HomeAssistant, HomeAssistant OS and Supervisor (described in the latest section) 

1. Go to `Settings > Add-ons > AMR2MQTT`
2. Click on 'Start'
3. Open the Logs tab and click on the Refresh button so you get always the latest
4. See the error in the logs section below

**Expected behavior**
AMR2MQTT successfully connects to Mosquitto MQTT broker.

**Logs**

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: AMR2MQTT
 AMR2MQTT for Home Assistant
-----------------------------------------------------------
 Add-on version: 2.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (amd64 / qemux86-64)
 Home Assistant Core: 2023.7.3
 Home Assistant Supervisor: 2023.07.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to DEBUG
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/02-set-timezone.sh
[08:13:59] INFO: Configuring timezone
cont-init: info: /etc/cont-init.d/02-set-timezone.sh exited 0
cont-init: info: running /etc/cont-init.d/30-config.sh
[08:13:59] DEBUG: Validate config and look for suggestions
[08:14:00] INFO: Ensure MQTT broker is reachable at core-mosquitto:1883 (60s timeout)
cont-init: info: /etc/cont-init.d/30-config.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun amr2mqtt (no readiness notification)
services-up: info: copying legacy longrun rtl_tcp (no readiness notification)
s6-rc: info: service legacy-services successfully started
[08:14:00] DEBUG: Setting MQTT details...
[08:14:00] INFO: Starting rtl_tcp daemon...
No supported devices found.
[08:14:00] WARNING: Halt add-on with exit code 1
s6-rc: info: service legacy-services: stopping
[08:14:00] INFO: Service restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Environment (please complete the following information):**

- Add-on version: 2.1.2
- Home Assistant version: 2023.7.3
- Supervisor version: 2023.07.1
- Operating System: Home Assistant 10.3

**Additional context**

What I have tried (several times)?

- While I know restarting HomeAssistant will not restart the Docker containers for this add-on I have restarted it several times just in case
- Restart both: the Mosquitto MQTT add-on and this AMR2MQTT add-on

I have the Ring-MQTT with Video Streaming add-on installed and is talking nicely with Mosquitto MQTT broker so the problem does not seem to be that add-on.

UPD: today I updated to the latest `2023.8.0` version and the following message popped up which might be part of the issue: 

> Discovered entities with a name that starts with the device name
> This stops working in version 2024.2.0. Please address before upgrading.
> Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped of the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.
> 
> List of affected entities:
> 
> sensor.energy_meter_consumption
> sensor.water_meter_consumption
> sensor.energy_meter_last_interval_consumption
> Warning - 8/2/2023

**Comment by ve6rah** [comment]
https://github.com/mdegat01/addon-amr2mqtt/issues/97
