### ISSUE TITLE
MQTT discovery messages need to be updated for new Home Assistant

### ISSUE THREAD

**Issue by agoode** [mdegat01/addon-amr2mqtt#97]
**Describe the bug**
Home Assistant now prints this warning in the UI:

This stops working in version 2024.2.0. Please address before upgrading.

Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped of the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:
- sensor.gas_meter_consumption

**To Reproduce**

Look at logs in Home Assistant.

**Expected behavior**

This warning isn't present.

**Logs**

```
MQTT entity name starts with the device name in your config {'enabled_by_default': False, 'name': 'Gas Meter Protocol ID', 'state_class': <SensorStateClass.MEASUREMENT: 'measurement'>, 'unique_id': 'amr2mqtt_xx_ProtocolID', 'value_template': Template<template=({{ value_json.ProtocolID }}) renders=0>, 'entity_category': <EntityCategory.DIAGNOSTIC: 'diagnostic'>, 'availability': [{'topic': 'amr2mqtt/bridge/state', 'payload_available': 'online', 'payload_not_available': 'offline'}], 'device': {'identifiers': ['amr2mqtt_xx'], 'name': 'Gas Meter', 'sw_version': '2.1.2', 'via_device': 'AMR2MQTT', 'connections': []}, 'state_topic': 'amr2mqtt/xx', 'qos': 0, 'payload_not_available': 'offline', 'availability_mode': 'latest', 'encoding': 'utf-8', 'payload_available': 'online', 'force_update': False}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes 'Protocol ID'
```

**Environment (please complete the following information):**

- Add-on version: 2.1.2
- Home Assistant: 2023.8.0
- Supervisor version: 2023.07.1
- Operating system: Home Assistant OS 2023.8.0

**Additional context**

https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099

I'm guessing the fix involves removing most of the `{device_name}` prefixes in amr2mqtt.py.

**Comment by agoode** [comment]
Yes, this is still an issue.

**Comment by benklop** [comment]
still an issue.
